name: 'Patch Droidspaces for Kernel.'

runs:
  using: 'composite'
  steps:
      - name: Patch Droidspaces
        if: env.DROIDSPACES_ENABLE == 'true'
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/device_kernel/
          cp /tmp/Patches/Droidspaces/droidspaces.config ./arch/"${{ env.KERNEL_ARCH }}"/configs/

          if [[ "${{ env.SUSFS_ENABLE }}" == "true" ]]; then
            echo "[-] Detected that SuSFS has been enabled, which may cause Droidspaces to work abnormally."
          fi

          if ! grep -q "kernfs_create_link" "kernel/cgroup.c" || ! grep -q "kernfs_create_link" "kernel/cgroup/cgroup.c"; then
            if [[ -f "net/netfilter/xt_qtaguid.c" ]]; then
                spatch --sp-file fix_kernel_panic_in_xt_qtaguid.cocci --in-place net/netfilter/xt_qtaguid.c
                echo "[+] xt_qtaguid.c Patched."

            else
                echo "[-] You kernel havn't the file."

            fi

            if [[ -f "kernel/cgroup/cgroup.c" ]]; then
                spatch --sp-file fix_restore_cgroup_file prefix_handling.cocci --in-place kernel/cgroup/cgroup.c
                echo "[+] cgroup.c Patched."

            else
                spatch --sp-file fix_restore_cgroup_file prefix_handling.cocci --in-place kernel/cgroup.c
                echo "[+] cgroup.c Patched."

            fi
            echo "[+] Patched Droidspaces for your kernel successfully."

          else
            echo "[-] Detected kernel patched, Skipped."

          fi
