name: Build Redmi K20 Pro (LineageOS 22 A15)

on:
  workflow_call:
  workflow_dispatch:

env:
  # Device env
  DEVICE_NAME : "redmi_k20_pro"
  DEVICE_CODENAME : "raphael"

  CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androidkernel- CROSS_COMPILE_COMPAT=arm-linux-androidkernel-"
  EXTRA_CMDS : "ARCH=arm64 CC=clang LD=ld.lld AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip LLVM=1 LLVM_IAS=1 HOSTCC=clang HOSTCXX=clang++"

  KERNEL_SOURCE : "https://github.com/LineageOS/android_kernel_xiaomi_sm8150.git"
  KERNEL_BRANCH : "lineage-22.2"

  CLANG_SOURCE : "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r536225.tar.gz"
  CLANG_BRANCH : ""

  GCC_GNU : true
  GCC_64_SOURCE : "https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9.git"
  GCC_64_BRANCH : "lineage-19.1"
  GCC_32_SOURCE : "https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9.git"
  GCC_32_BRANCH : "lineage-19.1"

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "vendor/sm8150-perf_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  KERNELSU_SOURCE : ""
  KERNELSU_BRANCH : ""

  KERNELSU_AUTO_GET : "true"
  KERNELSU_AUTO_FORK : "resukisu" # xxksu, rsuntk , next, resukisu and sukisu

  SUSFS_ENABLE : true
  SUSFS_FIXED : false

  AK3_SOURCE : "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH : "master"

  BOOT_SOURCE : ""

  NEED_DTBO : false
  NEED_SAFE_DTBO : false

  ROM_TEXT : "lineageos22_a15"

  # Other env
  PYTHON_VERSION: "3" # Only 2(Ubuntu 22.04 and Ubuntu 20.04) or 3(Any OS Versions).

  PACK_METHOD: "Anykernel3" # Anykernel3 need SOURCE and BRANCH, MKBOOTIMG needn't it.
  PACK_KMODULES: "false" # if u want pack kernel modules (.ko) into Anykernel3.

  KERNELSU_METHOD: "shell" # shell, manual and only.

  PATCHES_SOURCE: "" # [your_name]/[your_patch] -> gooder123/NonGKI_Patcher
  PATCHES_BRANCH: "" # [your_branch] -> main

  SUSFS_FOLDER_FIXED: "" # Fill in your patch prefix directory here. Leave it blank if there isn't one. -> your_folder
  SUSFS_PATCH_FIXED: "" # Fill in your patches here. If there are multiple patches, please separate them with a comma. Leave it blank if there isn't one. -> patch1,patch2

  REKERNEL_ENABLE: "false" # if u need Re:Kernel.

  HOOK_METHOD: "syscall" # Manual hook method ->  syscall.

  KERNEL_PATCH: "false" # If your kernel version is <= 4.9, you have the option of enabling the patch to patch the kernel_write and kernel_read functions.

  KPM_ENABLE: "false" # Anyone devices.
  KPM_INLINE: "false" # Only use it for SukiSU-Ultra.
  KPM_KPATCH_NEXT: "false" # If u want hook KPatch-Next in build step.
  KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux" # If u want to use KPM Inline,so you need set patch exec file source -> raw.githubusercontent.com/Test/Test/patch .

  BASEBAND_GUARD_ENABLE: "false" #if u want prevent unauthorized writes to critical partitions/device nodes.
  BASEBAND_GUARD_BOOT: "false" #if u want to protect boot partition.

  GENERATE_DTB: "false" # if u kernel need DTB , but cannot auto generate it. (Only Anykernel3).
  GENERATE_CHIP: "qcom" # only supported for qcom and mediatek.

  BUILD_DEBUGGER: "false" # Output build errors.
  SKIP_PATCH: "false" # Ignore errors found in Patch Debugger.

  BUILD_OTHER_CONFIG: "true" # Merge config files.
  MERGE_CONFIG_FILES: "vendor/debugfs.config,vendor/xiaomi/sm8150-common.config,vendor/xiaomi/raphael.config"

  FREE_MORE_SPACE: "false" # if u want get more space, enabled it.

jobs:
  build-kernel:
    name: Redmi K20 Pro (LineageOS 22 A15)
    runs-on: ubuntu-latest # u can changed to ubuntu 22.04, and need container set ubuntu-latest
    # container: archlinux/archlinux:latest # if u need use arch linux -> archlinux/archlinux:latest or ubuntu 20.04 -> ubuntu:focal
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v6

      - name: ⌛️ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get neccssary tools
        uses: ./.github/workflows/build-ready

      - name: 🪝 Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs

      - name: 🔗 Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: 🪛 Extra Kernel Options
        run: |
          # Only ${{ env.DEVICE_NAME }} use it.
          cd $GITHUB_WORKSPACE/device_kernel
          # Nothing

      - name: 🔄 Build and use LineageOS DTC
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/LineageOS/android_external_dtc.git -b lineage-22.2 lineage_dtc --depth=1
          cd lineage_dtc
          make dtc NO_PYTHON=1
          chmod +x dtc
          DTC_ABS_PATH="$GITHUB_WORKSPACE/lineage_dtc/dtc"
          echo "[+] LineageOS DTC built at: $DTC_ABS_PATH"
          echo "EXTRA_CMDS=${{ env.EXTRA_CMDS }} DTC=$DTC_ABS_PATH" >> $GITHUB_ENV
          echo "[+] DTC variable set, kernel build will use LineageOS DTC."

      - name: 🧰 Patch Kernel of Re:Kernel
        uses: ./.github/workflows/patch-rekernel

      - name: 🔒 Patch Kernel of Baseband Guard
        uses: ./.github/workflows/patch-baseband-guard

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 🔩 Pack Process
        uses: ./.github/workflows/pack-process

      - name: ✏️ Upload Artifacts
        uses: ./.github/workflows/upload-files
